# Cloudflare Pages - Build Configuration

framework = "nextjs"
build_command = "npm run build:cloudflare"
build_output_directory = ".next"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-01-01"

[env.production]
  MEDUSA_BACKEND_URL = "https://kst-estampados.medusajs.app"
  NODE_VERSION = "18"

[env.preview]
  MEDUSA_BACKEND_URL = "https://kst-estampados.medusajs.app"
  NODE_VERSION = "18"
